services:
  frontend:
    build: ./frontend
    image: xgate-frontend
    ports:
      - "8088:80"
    depends_on:
      - backend
    environment:
      - BACKEND_URL=backend:8080
    networks:
      - xgate-net

  backend:
    build: ./backend
    image: xgate-backend
    restart: always
    environment:
      - XGATE_DATABASE_TYPE=mysql
      - XGATE_DATABASE_HOST=db
      - XGATE_DATABASE_PORT=3306
      - XGATE_DATABASE_USER=xgate_user
      - XGATE_DATABASE_PASSWORD=xgate_password
      - XGATE_DATABASE_NAME=xgate_db
      - XGATE_SERVER_PORT=8080
      - XGATE_JWT_SECRET=a_very_secret_key_for_docker
    ports:
      - "8080:8080"
    depends_on:
      db:
        condition: service_healthy
    networks:
      - xgate-net

  # --- MySQL 服务定义 ---
  db:
    image: mysql:8.0
    restart: always
    environment:
      MYSQL_DATABASE: xgate_db
      MYSQL_USER: xgate_user
      MYSQL_PASSWORD: xgate_password
      MYSQL_ROOT_PASSWORD: root_password
    ports:
      - "3306:3306"
    volumes:
      - xgate-db-data:/var/lib/mysql
    networks:
      - xgate-net
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "xgate_user", "--password=xgate_password"]
      interval: 5s
      timeout: 5s
      retries: 10

networks:
  xgate-net:
    driver: bridge

volumes:
  xgate-db-data: 