apiVersion: apps/v1
kind: Deployment
metadata:
  name: xgate
spec:
  replicas: 1
  selector:
    matchLabels:
      app: xgate
  template:
    metadata:
      labels:
        app: xgate
    spec:
      containers:
        - name: xgate
          image: ipowerink/xgate-allinone:latest
          # imagePullPolicy: always
          ports:
            - containerPort: 80
          env:
            # 基本配置
            - name: XGATE_SERVER_PORT
              value: "8080"
            - name: XGATE_JWT_SECRET
              value: "test-secret"
              
            # 数据库配置 - 使用 MySQL
            # 注意：如果 XGATE_DATABASE_TYPE=sqlite（默认值），则以下 MySQL 相关环境变量可以省略
            - name: XGATE_DATABASE_TYPE
              value: "mysql"
            - name: XGATE_DATABASE_HOST
              value: "mysql2.sqlpub.com"
            - name: XGATE_DATABASE_PORT
              value: "3307"
            - name: XGATE_DATABASE_USER
              value: "xgate_user"
            - name: XGATE_DATABASE_PASSWORD
              value: "Lvm9TbnuSWG6NVYD"
            - name: XGATE_DATABASE_NAME
              value: "xgate_db"
---
apiVersion: v1
kind: Service
metadata:
  name: xgate
spec:
  type: NodePort
  selector:
    app: xgate
  ports:
    - port: 80
      targetPort: 80
      nodePort: 30080 